{% set name = "spla" %}
{% set version = "1.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/eth-cscs/spla/archive/refs/tags/v{{ version }}.tar.gz
  sha256: de30e427d24c741e2e4fcae3d7668162056ac2574afed6522c0bb49d6f1d0f79

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_compatible('spla', max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
    - cmake >=3.11.0
  host:
    - {{ mpi }}
    - libcblas
  run:
    - {{ mpi }}

test:
  commands:
    - test -f "${PREFIX}/lib/libspla${SHLIB_EXT}"

about:
  home: https://github.com/AdhocMan/spla
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Specialized linear algebra library, tailored for computational material science codes.
  description: |
    SPLA provides specialized functions for distributed matrix multiplication, as required in some computational material science codes. It aims for maximum computation and communication overlap when possible and allows any combination of host and device pointers if compiled with GPU support. C++, C  and Fortran interfaces are available.

  doc_url: https://spla.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/eth-cscs/spla

extra:
  recipe-maintainers:
    - AdhocMan
    - ltalirz
